default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  encoding: utf8

development:
  <<: *default
  database: shouter_development

test:
  <<: *default
  database: shouter_test

production:
  <<: *default
  database: shouter_production
